{
    "gameId": 3650425155,
    "platformId": "NA1",
    "gameCreation": 1604687460838,
    "gameDuration": 1477,
    "queueId": 420,
    "mapId": 11,
    "seasonId": 13,
    "gameVersion": "10.22.341.643",
    "gameMode": "CLASSIC",
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "teamId": 100,
            "win": "Fail",
            "firstBlood": false,
            "firstTower": false,
            "firstInhibitor": false,
            "firstBaron": false,
            "firstDragon": false,
            "firstRiftHerald": false,
            "towerKills": 1,
            "inhibitorKills": 0,
            "baronKills": 0,
            "dragonKills": 0,
            "vilemawKills": 0,
            "riftHeraldKills": 0,
            "dominionVictoryScore": 0,
            "bans": [
                {
                    "championId": 51,
                    "pickTurn": 1
                },
                {
                    "championId": 141,
                    "pickTurn": 2
                },
                {
                    "championId": 58,
                    "pickTurn": 3
                },
                {
                    "championId": 147,
                    "pickTurn": 4
                },
                {
                    "championId": 360,
                    "pickTurn": 5
                }
            ]
        },
        {
            "teamId": 200,
            "win": "Win",
            "firstBlood": true,
            "firstTower": true,
            "firstInhibitor": false,
            "firstBaron": true,
            "firstDragon": true,
            "firstRiftHerald": true,
            "towerKills": 6,
            "inhibitorKills": 0,
            "baronKills": 1,
            "dragonKills": 4,
            "vilemawKills": 0,
            "riftHeraldKills": 2,
            "dominionVictoryScore": 0,
            "bans": [
                {
                    "championId": 236,
                    "pickTurn": 6
                },
                {
                    "championId": 28,
                    "pickTurn": 7
                },
                {
                    "championId": 420,
                    "pickTurn": 8
                },
                {
                    "championId": 157,
                    "pickTurn": 9
                },
                {
                    "championId": 40,
                    "pickTurn": 10
                }
            ]
        }
    ],
    "participants": [
        {
            "participantId": 1,
            "teamId": 100,
            "championId": 67,
            "spell1Id": 7,
            "spell2Id": 4,
            "stats": {
                "participantId": 1,
                "win": false,
                "item0": 3153,
                "item1": 2031,
                "item2": 1043,
                "item3": 1054,
                "item4": 0,
                "item5": 3006,
                "item6": 3363,
                "kills": 0,
                "deaths": 3,
                "assists": 2,
                "largestKillingSpree": 0,
                "largestMultiKill": 0,
                "killingSprees": 0,
                "longestTimeSpentLiving": 801,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 60379,
                "magicDamageDealt": 108,
                "physicalDamageDealt": 52809,
                "trueDamageDealt": 7461,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 5054,
                "magicDamageDealtToChampions": 108,
                "physicalDamageDealtToChampions": 3888,
                "trueDamageDealtToChampions": 1057,
                "totalHeal": 2327,
                "totalUnitsHealed": 4,
                "damageSelfMitigated": 5941,
                "damageDealtToObjectives": 840,
                "damageDealtToTurrets": 840,
                "visionScore": 14,
                "timeCCingOthers": 2,
                "totalDamageTaken": 12944,
                "magicalDamageTaken": 2505,
                "physicalDamageTaken": 10215,
                "trueDamageTaken": 222,
                "goldEarned": 7207,
                "goldSpent": 6500,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 145,
                "neutralMinionsKilled": 4,
                "neutralMinionsKilledTeamJungle": 4,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 6,
                "champLevel": 11,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 7,
                "wardsKilled": 1,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8005,
                "perk0Var1": 341,
                "perk0Var2": 243,
                "perk0Var3": 97,
                "perk1": 9111,
                "perk1Var1": 149,
                "perk1Var2": 40,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 24,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8275,
                "perk4Var1": 7,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8236,
                "perk5Var1": 14,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 1,
                "creepsPerMinDeltas": {
                    "10-20": 6.1,
                    "0-10": 5.5
                },
                "xpPerMinDeltas": {
                    "10-20": 324.3,
                    "0-10": 251.2
                },
                "goldPerMinDeltas": {
                    "10-20": 299.5,
                    "0-10": 220.4
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.4999999999999998,
                    "0-10": -1.1499999999999997
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -106.05000000000001,
                    "0-10": 12.650000000000034
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 663,
                    "0-10": 240.3
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 286.9,
                    "0-10": -16
                },
                "role": "DUO_CARRY",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 2,
            "teamId": 100,
            "championId": 203,
            "spell1Id": 11,
            "spell2Id": 4,
            "stats": {
                "participantId": 2,
                "win": false,
                "item0": 3153,
                "item1": 2031,
                "item2": 0,
                "item3": 3006,
                "item4": 1412,
                "item5": 0,
                "item6": 3364,
                "kills": 2,
                "deaths": 4,
                "assists": 3,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 774,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 109533,
                "magicDamageDealt": 18899,
                "physicalDamageDealt": 83852,
                "trueDamageDealt": 6781,
                "largestCriticalStrike": 178,
                "totalDamageDealtToChampions": 8598,
                "magicDamageDealtToChampions": 1656,
                "physicalDamageDealtToChampions": 5548,
                "trueDamageDealtToChampions": 1393,
                "totalHeal": 9559,
                "totalUnitsHealed": 11,
                "damageSelfMitigated": 9380,
                "damageDealtToObjectives": 1797,
                "damageDealtToTurrets": 0,
                "visionScore": 26,
                "timeCCingOthers": 8,
                "totalDamageTaken": 20473,
                "magicalDamageTaken": 5382,
                "physicalDamageTaken": 13716,
                "trueDamageTaken": 1374,
                "goldEarned": 7744,
                "goldSpent": 7475,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 43,
                "neutralMinionsKilled": 95,
                "neutralMinionsKilledTeamJungle": 72,
                "neutralMinionsKilledEnemyJungle": 7,
                "totalTimeCrowdControlDealt": 186,
                "champLevel": 12,
                "visionWardsBoughtInGame": 4,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 7,
                "wardsKilled": 6,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8005,
                "perk0Var1": 692,
                "perk0Var2": 453,
                "perk0Var3": 239,
                "perk1": 9111,
                "perk1Var1": 144,
                "perk1Var2": 100,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 20,
                "perk2Var2": 40,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 119,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8232,
                "perk4Var1": 4,
                "perk4Var2": 20,
                "perk4Var3": 0,
                "perk5": 8275,
                "perk5Var1": 17,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 2,
                "creepsPerMinDeltas": {
                    "10-20": 2.4,
                    "0-10": 0.2
                },
                "xpPerMinDeltas": {
                    "10-20": 442.5,
                    "0-10": 311.8
                },
                "goldPerMinDeltas": {
                    "10-20": 313.5,
                    "0-10": 249.7
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1120.6999999999998,
                    "0-10": 457.59999999999997
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 3,
            "teamId": 100,
            "championId": 25,
            "spell1Id": 4,
            "spell2Id": 3,
            "stats": {
                "participantId": 3,
                "win": false,
                "item0": 3157,
                "item1": 0,
                "item2": 0,
                "item3": 3853,
                "item4": 0,
                "item5": 0,
                "item6": 3364,
                "kills": 0,
                "deaths": 4,
                "assists": 1,
                "largestKillingSpree": 0,
                "largestMultiKill": 0,
                "killingSprees": 0,
                "longestTimeSpentLiving": 1120,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 10716,
                "magicDamageDealt": 9888,
                "physicalDamageDealt": 827,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 5698,
                "magicDamageDealtToChampions": 5369,
                "physicalDamageDealtToChampions": 328,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 1112,
                "totalUnitsHealed": 4,
                "damageSelfMitigated": 7789,
                "damageDealtToObjectives": 53,
                "damageDealtToTurrets": 0,
                "visionScore": 18,
                "timeCCingOthers": 62,
                "totalDamageTaken": 10200,
                "magicalDamageTaken": 2178,
                "physicalDamageTaken": 7493,
                "trueDamageTaken": 528,
                "goldEarned": 4489,
                "goldSpent": 3475,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 3,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 84,
                "champLevel": 10,
                "visionWardsBoughtInGame": 1,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 12,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8465,
                "perk0Var1": 788,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8463,
                "perk1Var1": 251,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8473,
                "perk2Var1": 208,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8451,
                "perk3Var1": 128,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8347,
                "perk4Var1": 0,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8345,
                "perk5Var1": 3,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8300,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 3,
                "creepsPerMinDeltas": {
                    "10-20": 0.1,
                    "0-10": 0
                },
                "xpPerMinDeltas": {
                    "10-20": 249.20000000000002,
                    "0-10": 266.1
                },
                "goldPerMinDeltas": {
                    "10-20": 181.6,
                    "0-10": 139.8
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.4999999999999998,
                    "0-10": -1.1499999999999997
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -106.05000000000001,
                    "0-10": 12.650000000000034
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 574.8,
                    "0-10": 115.5
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 286.9,
                    "0-10": -16
                },
                "role": "DUO_SUPPORT",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 4,
            "teamId": 100,
            "championId": 3,
            "spell1Id": 4,
            "spell2Id": 12,
            "stats": {
                "participantId": 4,
                "win": false,
                "item0": 3152,
                "item1": 3111,
                "item2": 3157,
                "item3": 1056,
                "item4": 1058,
                "item5": 0,
                "item6": 3340,
                "kills": 4,
                "deaths": 3,
                "assists": 2,
                "largestKillingSpree": 4,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 1034,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 103677,
                "magicDamageDealt": 96670,
                "physicalDamageDealt": 6295,
                "trueDamageDealt": 711,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 11550,
                "magicDamageDealtToChampions": 11039,
                "physicalDamageDealtToChampions": 233,
                "trueDamageDealtToChampions": 277,
                "totalHeal": 895,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 17670,
                "damageDealtToObjectives": 0,
                "damageDealtToTurrets": 0,
                "visionScore": 20,
                "timeCCingOthers": 25,
                "totalDamageTaken": 16990,
                "magicalDamageTaken": 5755,
                "physicalDamageTaken": 10638,
                "trueDamageTaken": 595,
                "goldEarned": 8881,
                "goldSpent": 8525,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 170,
                "neutralMinionsKilled": 4,
                "neutralMinionsKilledTeamJungle": 4,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 89,
                "champLevel": 14,
                "visionWardsBoughtInGame": 3,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 13,
                "wardsKilled": 2,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8124,
                "perk0Var1": 122,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8139,
                "perk1Var1": 925,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8120,
                "perk2Var1": 3,
                "perk2Var2": 30,
                "perk2Var3": 8,
                "perk3": 8134,
                "perk3Var1": 30,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 8473,
                "perk4Var1": 629,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8451,
                "perk5Var1": 172,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8400,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5003
            },
            "timeline": {
                "participantId": 4,
                "creepsPerMinDeltas": {
                    "10-20": 6.8,
                    "0-10": 7.199999999999999
                },
                "xpPerMinDeltas": {
                    "10-20": 577.5,
                    "0-10": 433
                },
                "goldPerMinDeltas": {
                    "10-20": 417,
                    "0-10": 273.7
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.2999999999999998,
                    "0-10": -0.6000000000000005
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 141.2,
                    "0-10": -42.60000000000002
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1007.2,
                    "0-10": 350.70000000000005
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 488.6,
                    "0-10": 154.70000000000002
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 5,
            "teamId": 100,
            "championId": 114,
            "spell1Id": 4,
            "spell2Id": 12,
            "stats": {
                "participantId": 5,
                "win": false,
                "item0": 1055,
                "item1": 3074,
                "item2": 3047,
                "item3": 3133,
                "item4": 1029,
                "item5": 1053,
                "item6": 3340,
                "kills": 2,
                "deaths": 12,
                "assists": 2,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 237,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 73333,
                "magicDamageDealt": 1074,
                "physicalDamageDealt": 67100,
                "trueDamageDealt": 5158,
                "largestCriticalStrike": 387,
                "totalDamageDealtToChampions": 12917,
                "magicDamageDealtToChampions": 744,
                "physicalDamageDealtToChampions": 8710,
                "trueDamageDealtToChampions": 3462,
                "totalHeal": 5499,
                "totalUnitsHealed": 6,
                "damageSelfMitigated": 20494,
                "damageDealtToObjectives": 6644,
                "damageDealtToTurrets": 4002,
                "visionScore": 6,
                "timeCCingOthers": 12,
                "totalDamageTaken": 23815,
                "magicalDamageTaken": 5330,
                "physicalDamageTaken": 16340,
                "trueDamageTaken": 2144,
                "goldEarned": 7810,
                "goldSpent": 7550,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 129,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 73,
                "champLevel": 12,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 5,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 384,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 231,
                "perk1Var2": 80,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 22,
                "perk2Var2": 40,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 167,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8473,
                "perk4Var1": 854,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8446,
                "perk5Var1": 705,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8400,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 5,
                "creepsPerMinDeltas": {
                    "10-20": 4.9,
                    "0-10": 5.3
                },
                "xpPerMinDeltas": {
                    "10-20": 342.1,
                    "0-10": 353.7
                },
                "goldPerMinDeltas": {
                    "10-20": 364.4,
                    "0-10": 217.4
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 970.4000000000001,
                    "0-10": 608
                },
                "role": "SOLO",
                "lane": "TOP"
            }
        },
        {
            "participantId": 6,
            "teamId": 200,
            "championId": 24,
            "spell1Id": 4,
            "spell2Id": 12,
            "stats": {
                "participantId": 6,
                "win": true,
                "item0": 2033,
                "item1": 3153,
                "item2": 1028,
                "item3": 3076,
                "item4": 3047,
                "item5": 3078,
                "item6": 3340,
                "kills": 7,
                "deaths": 2,
                "assists": 8,
                "largestKillingSpree": 7,
                "largestMultiKill": 2,
                "killingSprees": 1,
                "longestTimeSpentLiving": 419,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 161582,
                "magicDamageDealt": 34524,
                "physicalDamageDealt": 115100,
                "trueDamageDealt": 11957,
                "largestCriticalStrike": 12,
                "totalDamageDealtToChampions": 15388,
                "magicDamageDealtToChampions": 4400,
                "physicalDamageDealtToChampions": 10847,
                "trueDamageDealtToChampions": 140,
                "totalHeal": 3222,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 15458,
                "damageDealtToObjectives": 23722,
                "damageDealtToTurrets": 4526,
                "visionScore": 19,
                "timeCCingOthers": 17,
                "totalDamageTaken": 18895,
                "magicalDamageTaken": 4196,
                "physicalDamageTaken": 12756,
                "trueDamageTaken": 1941,
                "goldEarned": 11662,
                "goldSpent": 10033,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 153,
                "neutralMinionsKilled": 32,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 24,
                "totalTimeCrowdControlDealt": 144,
                "champLevel": 15,
                "visionWardsBoughtInGame": 4,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 7,
                "wardsKilled": 1,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 1,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 585,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 722,
                "perk1Var2": 300,
                "perk1Var3": 0,
                "perk2": 9104,
                "perk2Var1": 13,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8299,
                "perk3Var1": 499,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8345,
                "perk4Var1": 3,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8304,
                "perk5Var1": 9,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8300,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 6,
                "creepsPerMinDeltas": {
                    "10-20": 6.1,
                    "0-10": 6
                },
                "xpPerMinDeltas": {
                    "10-20": 630.9,
                    "0-10": 421.79999999999995
                },
                "goldPerMinDeltas": {
                    "10-20": 556.8,
                    "0-10": 309.7
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 995.4000000000001,
                    "0-10": 470.7
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 7,
            "teamId": 200,
            "championId": 22,
            "spell1Id": 4,
            "spell2Id": 7,
            "stats": {
                "participantId": 7,
                "win": true,
                "item0": 3140,
                "item1": 3508,
                "item2": 3085,
                "item3": 1055,
                "item4": 3006,
                "item5": 0,
                "item6": 3363,
                "kills": 3,
                "deaths": 1,
                "assists": 6,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 1336,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 103733,
                "magicDamageDealt": 892,
                "physicalDamageDealt": 91663,
                "trueDamageDealt": 11178,
                "largestCriticalStrike": 344,
                "totalDamageDealtToChampions": 15294,
                "magicDamageDealtToChampions": 892,
                "physicalDamageDealtToChampions": 14012,
                "trueDamageDealtToChampions": 390,
                "totalHeal": 1963,
                "totalUnitsHealed": 3,
                "damageSelfMitigated": 5642,
                "damageDealtToObjectives": 7667,
                "damageDealtToTurrets": 4134,
                "visionScore": 23,
                "timeCCingOthers": 34,
                "totalDamageTaken": 9682,
                "magicalDamageTaken": 3770,
                "physicalDamageTaken": 5267,
                "trueDamageTaken": 645,
                "goldEarned": 9705,
                "goldSpent": 8700,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 170,
                "neutralMinionsKilled": 20,
                "neutralMinionsKilledTeamJungle": 12,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 508,
                "champLevel": 13,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 7,
                "wardsKilled": 3,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 1,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8008,
                "perk0Var1": 2,
                "perk0Var2": 20,
                "perk0Var3": 0,
                "perk1": 8009,
                "perk1Var1": 1544,
                "perk1Var2": 500,
                "perk1Var3": 0,
                "perk2": 9103,
                "perk2Var1": 24,
                "perk2Var2": 20,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 231,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8304,
                "perk4Var1": 12,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8410,
                "perk5Var1": 107,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8300,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5003
            },
            "timeline": {
                "participantId": 7,
                "creepsPerMinDeltas": {
                    "10-20": 8,
                    "0-10": 6.6
                },
                "xpPerMinDeltas": {
                    "10-20": 502.3,
                    "0-10": 252.10000000000002
                },
                "goldPerMinDeltas": {
                    "10-20": 421.6,
                    "0-10": 238.7
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.4999999999999998,
                    "0-10": 1.1499999999999997
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 106.05000000000001,
                    "0-10": -12.650000000000034
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 535.8,
                    "0-10": 184.2
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -286.9,
                    "0-10": 16
                },
                "role": "DUO_CARRY",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 8,
            "teamId": 200,
            "championId": 99,
            "spell1Id": 4,
            "spell2Id": 21,
            "stats": {
                "participantId": 8,
                "win": true,
                "item0": 1056,
                "item1": 3285,
                "item2": 3157,
                "item3": 3111,
                "item4": 2055,
                "item5": 0,
                "item6": 3363,
                "kills": 2,
                "deaths": 3,
                "assists": 7,
                "largestKillingSpree": 2,
                "largestMultiKill": 1,
                "killingSprees": 1,
                "longestTimeSpentLiving": 632,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 96396,
                "magicDamageDealt": 78722,
                "physicalDamageDealt": 13443,
                "trueDamageDealt": 4230,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 14048,
                "magicDamageDealtToChampions": 12281,
                "physicalDamageDealtToChampions": 1766,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 1353,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 7946,
                "damageDealtToObjectives": 5435,
                "damageDealtToTurrets": 3542,
                "visionScore": 20,
                "timeCCingOthers": 51,
                "totalDamageTaken": 8996,
                "magicalDamageTaken": 6685,
                "physicalDamageTaken": 2004,
                "trueDamageTaken": 306,
                "goldEarned": 8488,
                "goldSpent": 7650,
                "turretKills": 2,
                "inhibitorKills": 0,
                "totalMinionsKilled": 153,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 347,
                "champLevel": 14,
                "visionWardsBoughtInGame": 2,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 9,
                "wardsKilled": 2,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 1,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8229,
                "perk0Var1": 1421,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8226,
                "perk1Var1": 250,
                "perk1Var2": 1184,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8236,
                "perk3Var1": 24,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8313,
                "perk4Var1": 0,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8345,
                "perk5Var1": 3,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8300,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5003
            },
            "timeline": {
                "participantId": 8,
                "creepsPerMinDeltas": {
                    "10-20": 5.5,
                    "0-10": 7.800000000000001
                },
                "xpPerMinDeltas": {
                    "10-20": 436.3,
                    "0-10": 475.6
                },
                "goldPerMinDeltas": {
                    "10-20": 320.3,
                    "0-10": 251.3
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.2999999999999998,
                    "0-10": 0.6000000000000005
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -141.2,
                    "0-10": 42.60000000000002
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 518.6,
                    "0-10": 196
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -488.6,
                    "0-10": -154.70000000000002
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 9,
            "teamId": 200,
            "championId": 44,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "participantId": 9,
                "win": true,
                "item0": 3860,
                "item1": 3047,
                "item2": 3024,
                "item3": 3067,
                "item4": 2055,
                "item5": 3114,
                "item6": 3364,
                "kills": 0,
                "deaths": 1,
                "assists": 10,
                "largestKillingSpree": 0,
                "largestMultiKill": 0,
                "killingSprees": 0,
                "longestTimeSpentLiving": 1334,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 15949,
                "magicDamageDealt": 5657,
                "physicalDamageDealt": 4695,
                "trueDamageDealt": 5596,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 2890,
                "magicDamageDealtToChampions": 1774,
                "physicalDamageDealtToChampions": 560,
                "trueDamageDealtToChampions": 556,
                "totalHeal": 3272,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 5945,
                "damageDealtToObjectives": 1507,
                "damageDealtToTurrets": 227,
                "visionScore": 27,
                "timeCCingOthers": 13,
                "totalDamageTaken": 5805,
                "magicalDamageTaken": 2524,
                "physicalDamageTaken": 2768,
                "trueDamageTaken": 513,
                "goldEarned": 5664,
                "goldSpent": 4250,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 25,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 33,
                "champLevel": 11,
                "visionWardsBoughtInGame": 2,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 13,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 1,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8439,
                "perk0Var1": 103,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8463,
                "perk1Var1": 476,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8429,
                "perk2Var1": 51,
                "perk2Var2": 18,
                "perk2Var3": 12,
                "perk3": 8453,
                "perk3Var1": 400,
                "perk3Var2": 304,
                "perk3Var3": 0,
                "perk4": 8126,
                "perk4Var1": 209,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8106,
                "perk5Var1": 5,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5002,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 9,
                "creepsPerMinDeltas": {
                    "10-20": 1.2000000000000002,
                    "0-10": 1.2000000000000002
                },
                "xpPerMinDeltas": {
                    "10-20": 283.3,
                    "0-10": 239.89999999999998
                },
                "goldPerMinDeltas": {
                    "10-20": 237.3,
                    "0-10": 143.6
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.4999999999999998,
                    "0-10": 1.1499999999999997
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 106.05000000000001,
                    "0-10": -12.650000000000034
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 128.2,
                    "0-10": 203.60000000000002
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -286.9,
                    "0-10": 16
                },
                "role": "DUO_SUPPORT",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 10,
            "teamId": 200,
            "championId": 421,
            "spell1Id": 11,
            "spell2Id": 4,
            "stats": {
                "participantId": 10,
                "win": true,
                "item0": 1400,
                "item1": 2031,
                "item2": 3812,
                "item3": 3111,
                "item4": 1031,
                "item5": 3814,
                "item6": 3364,
                "kills": 14,
                "deaths": 1,
                "assists": 7,
                "largestKillingSpree": 7,
                "largestMultiKill": 2,
                "killingSprees": 2,
                "longestTimeSpentLiving": 977,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 112519,
                "magicDamageDealt": 3441,
                "physicalDamageDealt": 89123,
                "trueDamageDealt": 19955,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 17154,
                "magicDamageDealtToChampions": 0,
                "physicalDamageDealtToChampions": 13375,
                "trueDamageDealtToChampions": 3779,
                "totalHeal": 15103,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 20597,
                "damageDealtToObjectives": 30648,
                "damageDealtToTurrets": 1065,
                "visionScore": 21,
                "timeCCingOthers": 25,
                "totalDamageTaken": 25340,
                "magicalDamageTaken": 4260,
                "physicalDamageTaken": 17723,
                "trueDamageTaken": 3356,
                "goldEarned": 12477,
                "goldSpent": 11325,
                "turretKills": 2,
                "inhibitorKills": 0,
                "totalMinionsKilled": 18,
                "neutralMinionsKilled": 101,
                "neutralMinionsKilledTeamJungle": 64,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 185,
                "champLevel": 14,
                "visionWardsBoughtInGame": 2,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 3,
                "wardsKilled": 4,
                "firstBloodKill": true,
                "firstBloodAssist": false,
                "firstTowerKill": true,
                "firstTowerAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 1,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 9923,
                "perk0Var1": 46,
                "perk0Var2": 85,
                "perk0Var3": 0,
                "perk1": 8126,
                "perk1Var1": 676,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 18,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8105,
                "perk3Var1": 13,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 8275,
                "perk4Var1": 18,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8232,
                "perk5Var1": 4,
                "perk5Var2": 10,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8200,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 10,
                "creepsPerMinDeltas": {
                    "10-20": 1.3,
                    "0-10": 0.5
                },
                "xpPerMinDeltas": {
                    "10-20": 584.3,
                    "0-10": 384.7
                },
                "goldPerMinDeltas": {
                    "10-20": 638.5,
                    "0-10": 354.4
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1088,
                    "0-10": 726.5
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        }
    ],
    "participantIdentities": [
        {
            "participantId": 1,
            "player": {
                "platformId": "NA1",
                "accountId": "y_lSPFCk8EEIDVUTY8QAlSgtC6uXNIXvLkdm1nkIqkG_W0I",
                "summonerName": "Vayne Sup",
                "summonerId": "JBMGUcBX-spk_WN6ReuNHRIgYYgowGCdB4X--jrmi2mOnfU",
                "currentPlatformId": "NA1",
                "currentAccountId": "y_lSPFCk8EEIDVUTY8QAlSgtC6uXNIXvLkdm1nkIqkG_W0I",
                "matchHistoryUri": "/v1/stats/player_history/NA1/226722198",
                "profileIcon": 4803
            }
        },
        {
            "participantId": 2,
            "player": {
                "platformId": "NA1",
                "accountId": "Twsg9We5Ce77MPhdWddPnps2pc9PxweUC6LcH1LcvRGCh90",
                "summonerName": "JJtheBigThot",
                "summonerId": "f-YeFca2z-xIsS4HStIJEvEp22dQUuojHVrcvBXFpRT-unk",
                "currentPlatformId": "NA1",
                "currentAccountId": "Twsg9We5Ce77MPhdWddPnps2pc9PxweUC6LcH1LcvRGCh90",
                "matchHistoryUri": "/v1/stats/player_history/NA1/213581036",
                "profileIcon": 1440
            }
        },
        {
            "participantId": 3,
            "player": {
                "platformId": "NA1",
                "accountId": "9BeWZB2kB1nsfvGIr9lx-y7Fo6RpPufUGos-vDfxA-k8BaY",
                "summonerName": "PlzNoMoar",
                "summonerId": "ByLo_RkWms6R8xl_OSsZo4utzf9QVghqhoeHq5936fsvS-Q",
                "currentPlatformId": "NA1",
                "currentAccountId": "9BeWZB2kB1nsfvGIr9lx-y7Fo6RpPufUGos-vDfxA-k8BaY",
                "matchHistoryUri": "/v1/stats/player_history/NA1/219937825",
                "profileIcon": 4057
            }
        },
        {
            "participantId": 4,
            "player": {
                "platformId": "NA1",
                "accountId": "d8O319SYwf4LwKsbuz8mCRqFcyXaKlS-tW7eUJrKiAWkxlw",
                "summonerName": "Tatsuo3325",
                "summonerId": "OUf50mUqIQrwjl7MhOXud7HySIWEpoDOen8UtK5GcYbn9zE",
                "currentPlatformId": "NA1",
                "currentAccountId": "d8O319SYwf4LwKsbuz8mCRqFcyXaKlS-tW7eUJrKiAWkxlw",
                "matchHistoryUri": "/v1/stats/player_history/NA1/239587986",
                "profileIcon": 4782
            }
        },
        {
            "participantId": 5,
            "player": {
                "platformId": "NA",
                "accountId": "JrycxZG6NIZnxvy3OyfPtTy25oZx8SASGnrJkwPQV4TQhQ",
                "summonerName": "KUANG XlAO GOU",
                "summonerId": "P6i7IXUxIkQwci-kuGIfXeaY76Rw0h6OEvJRubSurvvrK5U",
                "currentPlatformId": "NA1",
                "currentAccountId": "JrycxZG6NIZnxvy3OyfPtTy25oZx8SASGnrJkwPQV4TQhQ",
                "matchHistoryUri": "/v1/stats/player_history/NA/38309946",
                "profileIcon": 4574
            }
        },
        {
            "participantId": 6,
            "player": {
                "platformId": "NA1",
                "accountId": "0Lf0ROtnClzbF_fI4VSvhVBh-WlViFjw-KPp2_UnZDrFAA",
                "summonerName": "Aika Tsube",
                "summonerId": "fM7HWVoXs6HtPAfy17uYCoz7fAa1YhyAUa7kPIr_wvTlxIQ",
                "currentPlatformId": "NA1",
                "currentAccountId": "0Lf0ROtnClzbF_fI4VSvhVBh-WlViFjw-KPp2_UnZDrFAA",
                "matchHistoryUri": "/v1/stats/player_history/NA1/42567730",
                "profileIcon": 4801
            }
        },
        {
            "participantId": 7,
            "player": {
                "platformId": "EUW1",
                "accountId": "rmOZY3x1DYPTwXMwuP174cm2TPOz_1Yxp6TemQ0Ku050kg",
                "summonerName": "DeBlackProphet",
                "summonerId": "zkDJASJDXh2kePCZuGLzW32OpjqsgRuG7WoGHcXb0teOOYw",
                "currentPlatformId": "NA1",
                "currentAccountId": "kbq2MZ2pRKYaUixwdmuK2GEz04h89HDGl4RnnCe6fH5kyhtg7Zb-_ncp",
                "matchHistoryUri": "/v1/stats/player_history/EUW1/33976757",
                "profileIcon": 4367
            }
        },
        {
            "participantId": 8,
            "player": {
                "platformId": "NA1",
                "accountId": "cKA1WklPLfIgRBQEJKCYtgHT2iLpyLc3TuoXj-ubq0DM0q8",
                "summonerName": "Sexiest",
                "summonerId": "dsYR7NAop5mDXwye-TnN-xZIghm7dVmi2TJPp0gPsJfneVA",
                "currentPlatformId": "NA1",
                "currentAccountId": "cKA1WklPLfIgRBQEJKCYtgHT2iLpyLc3TuoXj-ubq0DM0q8",
                "matchHistoryUri": "/v1/stats/player_history/NA1/213295356",
                "profileIcon": 4363
            }
        },
        {
            "participantId": 9,
            "player": {
                "platformId": "NA",
                "accountId": "4gvdCKdnMnT2i7A9gupgbretYUb7j57wLTjNtsocOKyTZw",
                "summonerName": "TSM Nightblue3",
                "summonerId": "XEqoOtbQNxB3kqurl2QhajtIL4x03n1AwLcPnqEBZKHND6E",
                "currentPlatformId": "NA1",
                "currentAccountId": "4gvdCKdnMnT2i7A9gupgbretYUb7j57wLTjNtsocOKyTZw",
                "matchHistoryUri": "/v1/stats/player_history/NA/38246520",
                "profileIcon": 4077
            }
        },
        {
            "participantId": 10,
            "player": {
                "platformId": "NA",
                "accountId": "9FQMydd02nsj6vdeQdjRN0SyIT44aE4RJCeGyxt2vDFDUA",
                "summonerName": "I CAN BENCH 450",
                "summonerId": "RuVvxAY2EgjOYJ24GKmR0f9GZX9jzUfbpQWLux5GN0abWw0",
                "currentPlatformId": "NA1",
                "currentAccountId": "9FQMydd02nsj6vdeQdjRN0SyIT44aE4RJCeGyxt2vDFDUA",
                "matchHistoryUri": "/v1/stats/player_history/NA/34635075",
                "profileIcon": 4759
            }
        }
    ]
}